"""ForgeAssembler core — framework-agnostic data model, detection, and concat."""

from .about import (
    ABOUT_MARKDOWN,
    APP_NAME,
    TAGLINE,
    VERSION,
    about_title,
)
from .concat_funscript import (
    FunscriptPart,
    concat_funscripts,
    read_funscript,
    write_funscript,
)
from .concat_video import (
    FfmpegCommand,
    FfmpegInput,
    build_ffmpeg_command,
    forge_video,
)
from .detect import (
    DetectedClip,
    categorize_channels,
    detect_file,
    detect_folder,
)
from .filters import (
    bug_overlay_filter,
    bug_prepare_filter,
    concat_filter,
    corner_position_expr,
    fade_to_black_audio_acrossfade,
    fade_to_black_xfade,
    image_overlay_filter,
    loudnorm_filter,
    normalize_segment_filter,
)
from .joiners import REGISTRY as JOINER_REGISTRY
from .joiners import Joiner, JoinerSpec, all_specs as joiner_specs, instantiate as instantiate_joiner
from .project import (
    FRAME_RATE_KEYS,
    QUALITY_CRF,
    RESOLUTION_KEYS,
    RESOLUTION_PIXELS,
    AudioLayer,
    BugOverlay,
    Joiner as ProjectJoiner,  # alias to avoid clash with joiners.Joiner
    Metadata,
    Output,
    OutputChannels,
    Overlay,
    Project,
    PROJECT_VERSION,
    Segment,
    ValidationIssue,
    is_still_image,
    new_id,
    validate,
)

__all__ = [
    "ABOUT_MARKDOWN",
    "APP_NAME",
    "AudioLayer",
    "BugOverlay",
    "DetectedClip",
    "FfmpegCommand",
    "FfmpegInput",
    "FRAME_RATE_KEYS",
    "FunscriptPart",
    "JOINER_REGISTRY",
    "Joiner",
    "JoinerSpec",
    "Metadata",
    "Output",
    "OutputChannels",
    "Overlay",
    "PROJECT_VERSION",
    "Project",
    "ProjectJoiner",
    "QUALITY_CRF",
    "RESOLUTION_KEYS",
    "RESOLUTION_PIXELS",
    "Segment",
    "TAGLINE",
    "VERSION",
    "ValidationIssue",
    "about_title",
    "bug_overlay_filter",
    "bug_prepare_filter",
    "build_ffmpeg_command",
    "categorize_channels",
    "concat_filter",
    "concat_funscripts",
    "corner_position_expr",
    "detect_file",
    "detect_folder",
    "fade_to_black_audio_acrossfade",
    "fade_to_black_xfade",
    "forge_video",
    "image_overlay_filter",
    "instantiate_joiner",
    "is_still_image",
    "joiner_specs",
    "loudnorm_filter",
    "new_id",
    "normalize_segment_filter",
    "read_funscript",
    "validate",
    "write_funscript",
]
