"""ForgeAssembler core — framework-agnostic data model, detection, and concat."""

from .about import (
    ABOUT_MARKDOWN,
    APP_NAME,
    TAGLINE,
    VERSION,
    about_title,
)
from .concat_audio_estim import (
    AUDIO_ESTIM_CHANNELS,
    build_audio_estim_command,
    forge_audio_estim,
)
from .concat_funscript import (
    FunscriptPart,
    concat_funscripts,
    forge_funscripts,
    read_funscript,
    write_funscript,
)
from .chapters import (
    Chapter,
    build_chapters,
    write_ffmetadata,
)
from .concat_video import (
    FfmpegCommand,
    FfmpegInput,
    build_ffmpeg_command,
    forge_video,
)
from .detect import (
    DetectedClip,
    categorize_channels,
    detect_file,
    detect_folder,
    detect_folder_tree,
)
from .forge_bundle import (
    ForgeBundle,
    detect_forge_bundle,
    forge_bundle_to_segment,
    is_forge_bundle,
)
from .filters import (
    bug_overlay_filter,
    bug_prepare_filter,
    concat_filter,
    corner_position_expr,
    fade_to_black_audio_acrossfade,
    fade_to_black_xfade,
    image_overlay_filter,
    loudnorm_filter,
    normalize_segment_filter,
)
from .heatmap import (
    compute_peak_speeds,
    heatmap_color,
    render_heatmap,
    write_heatmap,
)
from .joiners import REGISTRY as JOINER_REGISTRY
from .joiners import Joiner, JoinerSpec, all_specs as joiner_specs, instantiate as instantiate_joiner
from .project import (
    FRAME_RATE_KEYS,
    OVERLAY_POSITIONS,
    QUALITY_CRF,
    RESOLUTION_KEYS,
    RESOLUTION_PIXELS,
    AudioLayer,
    BugOverlay,
    Joiner as ProjectJoiner,  # alias to avoid clash with joiners.Joiner
    Metadata,
    Output,
    OutputChannels,
    Overlay,
    Project,
    PROJECT_VERSION,
    Section,
    SectionOverlay,
    Segment,
    ValidationIssue,
    is_still_image,
    new_id,
    prettify_filename_stem,
    validate,
)

__all__ = [
    "ABOUT_MARKDOWN",
    "APP_NAME",
    "AUDIO_ESTIM_CHANNELS",
    "AudioLayer",
    "BugOverlay",
    "Chapter",
    "DetectedClip",
    "ForgeBundle",
    "FfmpegCommand",
    "FfmpegInput",
    "FRAME_RATE_KEYS",
    "FunscriptPart",
    "JOINER_REGISTRY",
    "Joiner",
    "JoinerSpec",
    "Metadata",
    "Output",
    "OutputChannels",
    "Overlay",
    "PROJECT_VERSION",
    "Project",
    "ProjectJoiner",
    "QUALITY_CRF",
    "OVERLAY_POSITIONS",
    "RESOLUTION_KEYS",
    "RESOLUTION_PIXELS",
    "Section",
    "SectionOverlay",
    "Segment",
    "TAGLINE",
    "VERSION",
    "ValidationIssue",
    "about_title",
    "bug_overlay_filter",
    "bug_prepare_filter",
    "build_audio_estim_command",
    "build_chapters",
    "build_ffmpeg_command",
    "categorize_channels",
    "compute_peak_speeds",
    "concat_filter",
    "concat_funscripts",
    "corner_position_expr",
    "detect_file",
    "detect_folder",
    "detect_folder_tree",
    "detect_forge_bundle",
    "forge_bundle_to_segment",
    "is_forge_bundle",
    "fade_to_black_audio_acrossfade",
    "fade_to_black_xfade",
    "forge_audio_estim",
    "forge_funscripts",
    "forge_video",
    "heatmap_color",
    "image_overlay_filter",
    "instantiate_joiner",
    "is_still_image",
    "joiner_specs",
    "loudnorm_filter",
    "new_id",
    "normalize_segment_filter",
    "prettify_filename_stem",
    "read_funscript",
    "render_heatmap",
    "validate",
    "write_ffmetadata",
    "write_funscript",
    "write_heatmap",
]
